# Generated by Django 5.0.1 on 2024-01-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_posts_like_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
