# Generated by Django 5.0.1 on 2024-01-23 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0003_rename_posts_post"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
    ]
