# Generated by Django 5.0.1 on 2024-01-23 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0007_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
